### ISSUE TITLE
Events - Allow user to change status from (1) individual /events/:id page or (2) directly from the homepage events table row for the event

### ISSUE THREAD

**Issue by daisycrego** [daisycrego/jbg-admin#10]
## Events 
Allow user to change status from multiple UI locations:
(1) individual /events/:id page
(2) homepage - events table - each row should have an option to edit directly

## Todo
- [x] Add statuses to `Event` model:
- `No action`
- `Notified Zillow`
- `Zillow Approves Exemption`
- `Zillow Rejected Exemption`

How? 
- As string enum in the mongoose schema? 
- Did a lame little bit of research: 
  - https://stackoverflow.com/questions/43159336/what-to-do-with-enum-values-in-mongoose
  - https://mongoosejs.com/docs/validation.html
- Mongoose has several built-in validators.
  - Strings have `enum`, `match`, `minLength`, and `maxLength` validators.
```js
const breakfastSchema = new Schema({
  eggs: {
    type: Number,
    min: [6, 'Too few eggs'],
    max: 12
  },
  bacon: {
    type: Number,
    required: [true, 'Why no bacon?']
  },
  drink: {
    type: String,
    enum: ['Coffee', 'Tea'],
    required: function() {
      return this.bacon > 3;
    }
  }
});
```
 - You can configure the error message for individual validators in your schema.
```js
const breakfastSchema = new Schema({
  eggs: {
    type: Number,
    min: [6, 'Must be at least 6, got {VALUE}'],
    max: 12
  },
  drink: {
    type: String,
    enum: {
      values: ['Coffee', 'Tea'],
      message: '{VALUE} is not supported'
    }
  }
});
```
- [ ] Along with these enum options added to the schema, we need a form to edit the Event status. We need an individual one embedded in each event page and then a button to edit to each row in the database (you click the edit icon and then you see the dropdown).
- [ ] Dan's spec: The UI will give the admin the ability to mark each event as: `No action`, `Notified Zillow`, `Zillow Approves Exemption`, `Zillow Rejected Exemption`. All incoming events will be categorized as `No action` by default.
